//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SHOWART.RC
//
#define IDR_MAINFRAME                   2
#define IDR_BMPTYPE                     3
#define IDR_DIBTYPE                     4
#define IDR_BMPTYPE2                    4
#define IDR_TIFFTYPE                    5
#define IDR_BMPTYPE3                    5
#define IDR_GIFTYPE                     6
#define IDR_BMPTYPE1                    6
#define IDR_JPEGTYPE                    7
#define IDR_BMPTYPE4                    7
#define IDD_ABOUTBOX                    100
#define IDC_CHECK1                      102
#define IDC_CHECK2                      103
#define IDD_PREFERENCES                 103
#define IDC_EDIT1                       103
#define IDC_CHECK3                      104
#define IDC_GENERIC1                    104
#define IDC_EDIT2                       104
#define IDC_DEBUG_DISPLAY               104
#define IDD_VENUS                       105
#define IDC_CHECK4                      105
#define IDC_EDIT3                       105
#define IDC_CHECK5                      106
#define IDR_CONTEXTMENU                 106
#define IDC_EDIT4                       106
#define IDR_MAINFRAME1                  107
#define IDD_CUSTOM_OPEN                 107
#define IDC_CHECK6                      107
#define IDC_EDIT5                       107
#define IDC_CHECK_CACHING               107
#define IDC_SPIN1                       108
#define IDC_EDIT6                       108
#define IDD_KEY_COMMANDS                108
#define IDC_SKIP_BAD_ART                108
#define IDC_SLIDER1                     109
#define IDC_EDIT7                       109
#define IDC_LIST1                       110
#define IDC_EDIT8                       110
#define IDC_RICHEDIT1                   111
#define IDC_EDIT9                       111
#define IDD_SUPER_DELETE                111
#define IDC_EDIT10                      112
#define IDD_SUPER_SKIP                  112
#define IDC_PROGRESS1                   113
#define IDC_EDIT11                      113
#define IDC_C                           114
#define IDC_CLEAR_ALL                   114
#define IDC_EDIT12                      115
#define IDD_SUPER_MOVE                  115
#define IDC_D                           116
#define IDC_E                           117
#define IDC_F                           118
#define IDC_G                           119
#define IDC_J                           120
#define IDC_I                           121
#define IDC_B                           122
#define IDC_K                           123
#define IDC_H                           124
#define IDC_EDIT13                      125
#define IDC_L                           126
#define IDC_M                           127
#define IDC_EDIT14                      128
#define IDC_EDIT15                      129
#define IDC_EDIT16                      130
#define IDC_EDIT17                      131
#define IDC_EDIT18                      132
#define IDC_EDIT19                      133
#define IDC_EDIT20                      134
#define IDC_EDIT21                      135
#define IDC_EDIT22                      136
#define IDC_EDIT23                      137
#define IDC_EDIT24                      138
#define IDC_N                           139
#define IDC_P                           140
#define IDC_Q                           141
#define IDC_R                           142
#define IDC_S                           143
#define IDC_T                           144
#define IDC_W                           145
#define IDC_V                           146
#define IDC_O                           147
#define IDC_X                           148
#define IDC_U                           149
#define IDC_EDIT25                      150
#define IDC_EDIT26                      151
#define IDC_Y                           152
#define IDC_Z                           153
#define IDC_A                           154
#define IDC_MODE1                       154
#define IDC_DEL_AFTER_COPY              155
#define IDC_AUTOTIME                    156
#define IDC_EDITROOT                    156
#define IDC_RADIO1                      157
#define IDC_RADIO2                      158
#define IDC_EDIT27                      158
#define IDC_RADIO3                      159
#define IDC_EDIT28                      159
#define IDC_RADIO4                      160
#define IDC_EDIT29                      160
#define IDC_RADIO5                      161
#define IDC_EDIT30                      161
#define IDC_RADIO6                      162
#define IDC_EDIT31                      162
#define IDC_EDIT32                      163
#define IDC_JPEG_QUALITY                163
#define IDC_EDIT33                      164
#define IDC_EDIT34                      165
#define IDC_EDIT35                      166
#define IDC_EDIT36                      167
#define IDC_EDIT37                      168
#define IDC_EDIT38                      169
#define IDC_MODE2                       169
#define IDC_EDIT39                      170
#define IDC_MODE3                       170
#define IDC_N2                          171
#define IDC_O2                          172
#define IDC_Q2                          173
#define IDC_P2                          174
#define IDC_R2                          175
#define IDC_S2                          176
#define IDC_T2                          177
#define IDC_U2                          178
#define IDC_V2                          179
#define IDC_W2                          180
#define IDC_X2                          181
#define IDC_MODE4                       181
#define IDC_Y2                          182
#define IDC_MODE5                       182
#define IDC_Z2                          183
#define IDC_MODE6                       183
#define IDC_SCHEMES                     184
#define IDC_NEW_SCHEME                  185
#define IDC_ADD_SCHEME                  186
#define IDC_SPIN2                       187
#define IDC_MODE7                       187
#define IDC_VERSION                     188
#define IDC_SPIN3                       188
#define IDC_MODE8                       188
#define IDC_WHERE                       189
#define IDC_MODE9                       189
#define IDC_DEFAULT_DIR                 190
#define IDC_MODE10                      190
#define IDC_DEFAULT_DIR_ALWAYS_OPEN     191
#define IDC_MODE11                      191
#define IDC_MODE12                      192
#define IDC_MODE13                      193
#define IDC_MODE14                      195
#define IDC_MODE15                      196
#define IDC_MODE16                      197
#define IDC_MODE17                      198
#define IDC_MODE18                      199
#define IDC_MODE19                      200
#define IDC_MODE20                      201
#define IDC_MODE21                      202
#define IDC_MODE22                      203
#define IDC_SetAll                      204
#define IDC_MODE23                      205
#define IDC_MODE24                      206
#define IDC_MODE25                      207
#define IDC_MODE26                      208
#define IDC_MODE27                      209
#define IDC_MODE28                      210
#define IDC_MODE29                      211
#define IDC_MODE30                      212
#define IDC_MODE31                      213
#define IDC_MODE32                      214
#define IDC_MODE33                      215
#define IDC_MODE34                      216
#define IDC_MODE35                      217
#define IDC_MODE36                      218
#define IDC_MODE37                      219
#define IDC_DELETE_SCHEME               220
#define IDC_BUTTON1                     221
#define IDC_USE_BATCH_FILE              222
#define IDC_SAFECOPY                    223
#define ID_VIEW_FULLSCREEN              32769
#define ID_VIEW_TESTTETST               32770
#define ID_VIEW_FITTOWINDOW             32771
#define ID_VIEW_FITTOFULLSCREEN         32772
#define ID_EDIT_EMPTYCLIPBOARD          32773
#define ID_WINDOW_CLOSEALL              32774
#define ID_FILE_PREFERENCES             32775
#define ID_FILE_CLOSEALL                32776
#define ID_VIEW_FITALLTOWINDOW          32777
#define ID_CDROM_VENUS                  32778
#define ID_CDROM_VENUSAUTO              32779
#define ID_CDROM_TROPICALNUDE           32780
#define IDM_WALLPAPER                   32781
#define ID_FILE_KEY_COMMANDS            32782
#define ID                              32784
#define ID_FILE_SORT_NAME               32785
#define ID_FILE_SORT_DATE               32786
#define ID_FILE_SORT_SIZE               32787
#define ID_FILE_SORT_REVERSE            32788
#define ID_ROTATE_90                    32789
#define ID_ROTATE_180                   32790
#define ID_ROTATE_270                   32791
#define ID_SKIP_BACK                    32792
#define ID_SKIP_FORWARD                 32793
#define ID_SKIP_FORWARD_MORE            32794
#define ID_SKIP_BACK_MORE               32795
#define ID_SUPER_DELETE                 32796
#define ID_Menu                         32798
#define ID_VIEW_NO_SHRINK               32803
#define ID_VIEW_SHRINK8                 32804
#define ID_VIEW_SHRINK4                 32805
#define ID_VIEW_SHRINK2                 32806
#define ID_SUPER_SKIP                   32807
#define ID_EDIT_SUPERSKIP               32809
#define ID_SUPER_MOVE                   32812
#define ID_ACCELERATOR32815             32815
#define ID_SUPER_SKIP_DEFAULT           32816

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        120
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         223
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
